CREATE DATABASE IF NOT EXISTS apex_db;

USE apex_db;

CREATE TABLE IF NOT EXISTS users (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(100)  NOT NULL,
    email    VARCHAR(100)  NOT NULL UNIQUE,
    password VARCHAR(255)  NOT NULL,
    role     VARCHAR(20)   NOT NULL DEFAULT 'user'
);
